---
title: "Antes de comenzar"
output:
  html_document:
    toc: false
---

Para participar en este taller puedes instalar R (>4.0) y Rstudio (revisa las instrucción más abajo) o usar una instancia de R en RStudio Cloud.

#### Usando RStudio Cloud

Si quieres usar RStudio Cloud necesitarás una cuenta gratuita. Ingresa a [posit.cloud/](https://posit.cloud/) y sigue las instrucciones para registrarte. Ten en cuenta que la cuenta gratuita tiene un límite de uso de 15 horas por mes, te recomendamos no usar todas las horas antes del taller.

Durante el taller compartiremos un link a un proyecto de RStudio listo para usar. No es necesario que hagas nada más. 

#### Instalando R y RStudio

Para instalar R y RStudio sigue las instrucciones en [estos videos](https://www.youtube.com/playlist?list=PLRPB0ZzEYegOZivdelOuEn-R-XUN-DOjd) de [Danielle Navarro](https://djnavarro.net/).

Después instalar todo, tendrás que instalar algunos paquetes necesarios para el taller. Sigue estas instrucciones:

1. Abre RStudio
2. En la consola (el panel de la izquierda) escriba los siguientes comandos:

```{r, eval=FALSE}
install.packages("tidyverse")
install.packages("datos")
```

4. Haz click en Archivo -> Nuevo Archivo -> R Markdown. Haz clic en "Ok" para crear un nuevo archivo. 

5. RStudio te pedirá permiso para instalar varios paquetes. Adelante, hazlo. 

5. Puedes eliminar el archivo que acabas de crear.

6. Descarga [este proyecto](rstudio-project-pinguinos.zip) para trabajar durante el taller y extrae los archivos del .zip en la carpeta que prefieras (recomendamos no hacerlo en el escritorio).

7. Eso es todo. 
